# Name: Kyle Chan
# Project: Lab 5: Page/Offset Calculation
CC=gcc
CFLAGS=-g -Wall -Wextra

all: lab5

lab5: lab5.c
	$(CC) $(CFLAGS) -c lab5.c
	$(CC) $(CFLAGS) -o $@ lab5.o -lm

clean:
	rm -f lab5 lab5.o *~